### ISSUE TITLE
User creation works fine, but can't sign in

### ISSUE THREAD

**Issue by kmyhre** [jasperweyne/PiwigoOpenIdConnect#16]
Hi!

When I try to sign in using the OpenID Connect integration, the user is created as expected, but I can't seem to sign in with it: After authentication, the user is returned to Piwigo's main page and shown the regular "sign in" button as if nothing has happened.

There are no errors in Piwigo or OpenID Connect, but the admin usage logs show a user "user#0" to have signed in instead of the authenticated user. This "user#0" is not shown in the regular list of registered users.

Authorization code flow test works fine, but user creation test (after the first time) returns this warning:
```
Warning:  [mysql error 1062] Duplicate entry '0a96c301-f6ec-4e87-92d6-6d9817a013b5' for key 'sub'

INSERT  INTO `piwigo_oidc`
  (`sub`,`user_id`)
  VALUES('0a96c301-f6ec-4e87-92d6-6d9817a013b5','') in /gallery/include/dblayer/functions_mysqli.inc.php on line 847

Successful!
```

Is this a known problem, or is it an issue with my configuration?

**Comment by agademer** [comment]
I had the same problem here.

My first user creation probably failed because it was the same email as the admin email used when I installed piwigo.

Solution : 

Go to the database : 
```
sudo mariadb                 
MariaDB [piwigo_db]> use piwigo_db;          
MariaDB [piwigo_db]> select * from piwigo_oidc;
+---------------------------------------------+---------+
| sub                                         | user_id |
+---------------------------------------------+---------+
| k-SOMEHASHHERE                              |         |
+---------------------------------------------+---------+
```

=> We can see that user_id is void (should have you user number)

!!!  Warning, the next SQL query delete all the table (but I had only 1 row)
```
MariaDB [piwigo_db]> delete from piwigo_oidc;                          
Query OK, 1 row affected (0.001 sec)
```

=> Delete the user in the web interface
=> Recreate the user through OpenID plugin

you should NOT see the error message.

You can check the db
```
MariaDB [piwigo_db]> select * from piwigo_oidc;
+---------------------------------------------+---------+
| sub                                         | user_id |
+---------------------------------------------+---------+
| k-SOMEHASHHERE                              | 8       |
+---------------------------------------------+---------+
```

=> You can see that the user_id is correct

Now you can activate the flow and it should work !

**Comment by kmyhre** [comment]
Works like a charm, thanks @agademer!
