### ISSUE TITLE
PHP Error "Undefined index: OpenIdConnect in /plugins/OpenIdConnect/main.inc.php on line 195"

### ISSUE THREAD

**Issue by jochemp264** [jasperweyne/PiwigoOpenIdConnect#7]
After I enable the plugin, I can log in and out a few times. Suddenly, I received this error. When testing the flow, it gives me a Success message.
<img width="1440" alt="Schermafbeelding 2021-10-06 om 01 36 47" src="https://user-images.githubusercontent.com/66232866/136117112-001f39af-6660-469d-8fe9-ccbda60b4006.png">
 
EDIT: Piwigo itself gives me the message: "The communication to retrieve user data has failed with status code 429"

**Comment by jasperweyne** [comment]
Hi, thanks for reporting this problem! The OpenID Connect protocol receives a token that's used for login. That token specifies how long a user may be logged in for with that token. After that time has passed, the token must be refreshed. It seems that the refreshing goes wrong. Status code 429 seems like a HTTP status code, which would be 'HTTP 429 Too Many Requests'. Please check the settings of your authentication server to fix the underlying problem. Ofcourse, the error should be more "human readable" instead of this call stack, so I'll fix that in a later release.

**Comment by jochemp264** [comment]
I left this unattended for a few months because the project was on hold. Our Piwigo instance has moved to another, dedicated webserver. The problem doesn't exist here anymore so I guess it was a problem in the configuration of my old webserver, as I had several problems on that server with external services.
